version: "3.5"
# You should be able to find & replace all instances of ummon with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  ummon:
  ummon-private:

volumes:
  ummon:
#  ummon-db:

secrets:
  ummon_admin_password:
    name: ${STACK_NAME:-technocore}_ummon_admin_password
    external: true
#  ummon_ummon_db_password:
#    name: ${STACK_NAME:-technocore}_ummon_ummon_db_password
#    external: true
#  ummon_db_ummon_password:
#    name: ${STACK_NAME:-technocore}_ummon_db_ummon_password
#    external: true

services:
  ingress:
    networks:
      - ummon

  ummon:
    deploy:
      labels:
        - traefik.frontend.rule=$UMMON_ROUTING_LABEL
        - traefik.frontend.priority=$UMMON_ROUTING_LABEL_PRIORITY
        # You'll need to set applicaiton's port here.
        - traefik.port=8000
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_ummon
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - MQTT_USER=ummon
      - DOMAIN=${DOMAIN}
      - DJANGO_SUPERUSER_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - DJANGO_SUPERUSER_USERNAME=${ADMIN_USER}
      - DJANGO_SUPERUSER_EMAIL=${ADMIN_USER}@ummon.${DOMAIN}
      # Don't buffer STDout: https://unix.stackexchange.com/questions/182537/write-python-stdout-to-file-immediately
      - PYTHONUNBUFFERED=1
    image: ${image_provider:-scififarms}/technocore-ummon:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - ummon
      - ummon-private
    secrets:
    #  - source: ummon_ummon_db_password
    #    target: ummon_db_password
      - source: ummon_admin_password
        target: admin_password
    volumes:
      - ummon:/usr/src/app/data
      - ${DEV_MOUNT_UMMON_MIGRATIONS:-$EMPTY_MOUNT}
      - ${DEV_MOUNT_UMMON_INVENTORYTRACKER:-$EMPTY_MOUNT}
      - ${DEV_MOUNT_UMMON_CHASGIMQTT:-$EMPTY_MOUNT}
    # For Python Debugging
    # Also need to uncomment lines in manage.py and/or chasgimqtt/server.py.
    # Options for the debug toolbar can be enabled in settings.py and urls.py
    #ports:
    #  - 5678:5678
    #  - 5679:5679

  ummon_redis:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    image: redis:4-alpine
    networks:
      - ummon-private

  ## I'll want to move to a real DB at somepoint. For now, SQLite
  #ummon_db:
  #  deploy:
  #    labels:
  #      - com.ouroboros.enable=true
  #    mode: global
  #    restart_policy:
  #      condition: any
  #  #environment:
  #  image: ${image_provider:-scififarms}/technocore-ummon-db:${TAG:-latest}
  #  logging:
  #    driver: "${LOGGING_DRIVER}"
  #    options:
  #      tag: "{{.Name}}"
  #  networks:
  #    - ummon-private
  #  secrets:
  #    - source: ummon_db_admin_password
  #      target: admin_password
  #    - source: ummon_db_ummon_password
  #      target: ummon_password
  #  volumes:
  #    # Likely need to change this
  #    - ummon-db:/var/lib/ummon
