# Generated by Django 3.0.4 on 2020-03-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='msrp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
