# Generated by Django 3.0.4 on 2020-05-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_part_msrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seedship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range_start', models.BigIntegerField()),
                ('time_range_end', models.BigIntegerField()),
                ('calibration_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sensor')),
                ('seedship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Seedship')),
            ],
        ),
    ]
